//
//  PagesConfigurator.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PagesViewController: PagesPresenterOutput {
    
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    
    router.passDataToNextScene(segue: segue)
  }
}

extension PagesInteractor: PagesViewControllerOutput {
}

extension PagesPresenter: PagesInteractorOutput{
}

class PagesConfigurator {
    
  // MARK: - Object lifecycle
  
  static let sharedInstance = PagesConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: PagesViewController) {
    
    let router = PagesRouter()
    router.viewController = viewController
    
    let presenter = PagesPresenter()
    presenter.output = viewController
    
    let interactor = PagesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
