//
//  PagesPresenter.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PagesPresenterInput {
    
  func presentSomething(response: Pages.Something.Response)
}

protocol PagesPresenterOutput: class {
    
  func displaySomething(viewModel: Pages.Something.ViewModel)
}

class PagesPresenter: PagesPresenterInput {
    
  weak var output: PagesPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: Pages.Something.Response) {
    
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = Pages.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
