//
//  PagesWorker.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class PagesWorker {
    
  // MARK: - Business Logic
  
  func doSomeWork() {
    
    // NOTE: Do the work
  }
}
