//
//  PagesInteractor.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PagesInteractorInput {
    
    func doSomething(request: Pages.Something.Request)
    var list: [StuffModel]? { get set}
}

protocol PagesInteractorOutput {
    
    func presentSomething(response: Pages.Something.Response)
}

class PagesInteractor: PagesInteractorInput {
    
    var output: PagesInteractorOutput!
    var worker: PagesWorker!
    
    var list: [StuffModel]?
    
    // MARK: - Business logic
    
    func doSomething(request: Pages.Something.Request) {
        // NOTE: Create some Worker to do the work
        
        worker = PagesWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = Pages.Something.Response()
        output.presentSomething(response: response)
    }
}
