//
//  ScreenConfigurator.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ScreenViewController: ScreenPresenterOutput {
    
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    
    router.passDataToNextScene(segue: segue)
  }
}

extension ScreenInteractor: ScreenViewControllerOutput {
}

extension ScreenPresenter: ScreenInteractorOutput {
}

class ScreenConfigurator {
  // MARK: - Object lifecycle
  
  static let sharedInstance = ScreenConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ScreenViewController) {
    
    let router = ScreenRouter()
    router.viewController = viewController
    
    let presenter = ScreenPresenter()
    presenter.output = viewController
    
    let interactor = ScreenInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
