//
//  ScreenRouter.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScreenRouterInput {
    
    func addDefaultViewController()
    func addSelectedViewControlerWith(selectedItem: MenuItem)
}

class ScreenRouter: ScreenRouterInput {
    
    weak var viewController: ScreenViewController!
    
    // MARK: - Navigation
    
    func addDefaultViewController() {
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let listViewController = storyboard.instantiateViewController(withIdentifier: ListViewController.reuseIdentifier) as! ListViewController
        
        self.viewController.add(asChildViewController: listViewController, animated: false){}
    }
    
    func addSelectedViewControlerWith(selectedItem: MenuItem) {
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        switch selectedItem {
            
        case MenuItem.aboutUs:
            
            let aboutUsViewController =
                storyboard.instantiateViewController(withIdentifier: AboutUsViewController.reuseIdentifier) as! AboutUsViewController
            
            self.open(controller: aboutUsViewController)
            
            break
            
        case MenuItem.stuffList:
            
            let listViewController =
                storyboard.instantiateViewController(withIdentifier: ListViewController.reuseIdentifier) as! ListViewController
            
            self.open(controller: listViewController)
            
            break
            
        case MenuItem.settings:
            
            let settingsViewController =
                storyboard.instantiateViewController(withIdentifier: SettingsViewController.reuseIdentifier) as! SettingsViewController
            
            self.open(controller: settingsViewController)
            
            break
            
        }
    }
    
    func open(controller: UIViewController){
        
        let contoller = self.viewController.childViewControllers.first
        
        self.viewController.replace(asChildViewController: contoller!, to: controller)
    }
    
    // MARK: - Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with
        
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    func passDataToSomewhereScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router how to pass data to the next scene
        
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
