//
//  ScreenInteractor.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScreenInteractorInput {
    
  func doSomething(request: Screen.Something.Request)
}

protocol ScreenInteractorOutput {
    
  func presentSomething(response: Screen.Something.Response)
}

class ScreenInteractor: ScreenInteractorInput {
    
  var output: ScreenInteractorOutput!
  var worker: ScreenWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Screen.Something.Request) {
    
    // NOTE: Create some Worker to do the work
    
    worker = ScreenWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Screen.Something.Response()
    output.presentSomething(response: response)
  }
}
