//
//  MenuInteractor.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum MenuItem: String {
    
    case aboutUs = "About us"
    case stuffList = "Stuff list"
    case settings = "Settings"
}

protocol MenuInteractorInput {
    
    func fetchItems(request: Menu.Items.Request)
}

protocol MenuInteractorOutput {
    
    func presentItems(response: Menu.Items.Response)
}

class MenuInteractor: MenuInteractorInput {
    
    var output: MenuInteractorOutput!
    var worker: MenuWorker!
    
    // MARK: - Business logic
    
    func fetchItems(request: Menu.Items.Request) {
        
        let items = [MenuItem.aboutUs, MenuItem.stuffList, MenuItem.settings]
        let response = Menu.Items.Response(items: items)
        self.output.presentItems(response: response)
    }
}
