//
//  MenuModels.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Menu {
    
  struct Items{
    
    struct Request {
    }
    struct Response {
        
        var items: [MenuItem]
    }
    struct ViewModel {
        
        struct DisplayItem {
            
            var title: String
            var iconName: String
        }
        var displayedItems: [DisplayItem]
    }
  }
}
