//
//  MenuConfigurator.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension MenuViewController: MenuPresenterOutput {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        
        router.passDataToNextScene(segue: segue)
    }
}

extension MenuInteractor: MenuViewControllerOutput {
}

extension MenuPresenter: MenuInteractorOutput {
}

class MenuConfigurator {
    
    // MARK: - Object lifecycle
    
    static let sharedInstance = MenuConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(viewController: MenuViewController) { 
        
        let router = MenuRouter()
        router.viewController = viewController
        
        let presenter = MenuPresenter()
        presenter.output = viewController
        
        let interactor = MenuInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
