//
//  MenuPresenter.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum MenuIcon: String {
    
    case aboutus = "aboutus"
    case list = "list"
    case settings = "settings"
}


protocol MenuPresenterInput {
    
    func presentItems(response: Menu.Items.Response)
}

protocol MenuPresenterOutput: class {
    
    func displayItems(viewModel: Menu.Items.ViewModel)
}

class MenuPresenter: MenuPresenterInput {
    
    weak var output: MenuPresenterOutput!
    
    // MARK: - Presentation logic
    
    func presentItems(response: Menu.Items.Response) {
        
        let items = response.items
        let iconNames = [MenuIcon.aboutus, MenuIcon.list, MenuIcon.settings]
        
        var displayedItems: [Menu.Items.ViewModel.DisplayItem] = []
        
        for index in 0..<items.count {
            
            let title = items[index].rawValue
            let name = iconNames[index].rawValue
            let displayedItem = Menu.Items.ViewModel.DisplayItem(title: title, iconName: name)
            
            displayedItems.append(displayedItem)
        }
        
        let viewModel = Menu.Items.ViewModel(displayedItems: displayedItems)
        self.output.displayItems(viewModel: viewModel)
    }
}
