//
//  DetailInteractor.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailInteractorInput {
    
    func fetchDetail(request: Detail.Stuff.Request)
    var stuff: StuffModel! { get set }
}

protocol DetailInteractorOutput {
    
    func presentDetail(response: Detail.Stuff.Response)
}

class DetailInteractor: DetailInteractorInput {
    
    var output: DetailInteractorOutput!
    var worker: DetailWorker!
    
    var stuff: StuffModel!
    
    // MARK: - Business logic
    
    func fetchDetail(request: Detail.Stuff.Request) {
        
        let placeholderName = ImageNames.placeholder.rawValue
        
        let response = Detail.Stuff.Response(stuff: self.stuff, placeholderName: placeholderName)
        self.output.presentDetail(response: response)
    }
}
