//
//  DetailModels.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Detail{
    
    struct Stuff {
        
        struct Request {
            
        }
        struct Response {
            
            var stuff: StuffModel
            var placeholderName: String
        }
        struct ViewModel {
            
            struct DisplayStuff {
                
                var detail: String
                var imageUrl: String
            }
            
            var displayStuff: DisplayStuff
            var placeholderName: String
        }
    }
}
