//
//  DetailConfigurator.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension DetailViewController: DetailPresenterOutput {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        
        router.passDataToNextScene(segue: segue)
    }
}

extension DetailInteractor: DetailViewControllerOutput {
}

extension DetailPresenter: DetailInteractorOutput {
}

class DetailConfigurator {
    
    // MARK: - Object lifecycle
    
    static let sharedInstance = DetailConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(viewController: DetailViewController) {
        
        let router = DetailRouter()
        router.viewController = viewController
        
        let presenter = DetailPresenter()
        presenter.output = viewController
        
        let interactor = DetailInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
