//
//  ListModels.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct List {
    
    struct Stuff {
        
        struct Request {
            
            var searchText: String
        }
        struct Response {
            
            var stuffList: [StuffModel]
            var placeholderName: String
        }
        struct ViewModel {
            
            struct DisplayedStuff{
                
                var itemId: String
                var name: String
                var imageUrl: String
                var date: String
            }
            
            var displayedStuff: [DisplayedStuff]
            var placeholderName: String
        }
    }
}
