//
//  SettingsInteractor.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingsInteractorInput {
    
  func fetchImage(request: Settings.Image.Request)
}

protocol SettingsInteractorOutput {
    
  func presentImage(response: Settings.Image.Response)
}

class SettingsInteractor: SettingsInteractorInput {
    
  var output: SettingsInteractorOutput!
  var worker: SettingsWorker!
  
  // MARK: - Business logic
  
  func fetchImage(request: Settings.Image.Request) {
    
    let imageName = "settingsImage"
    
    let response = Settings.Image.Response(imageName: imageName)
    self.output.presentImage(response: response)
  }
}
