//
//  SettingsViewController.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingsViewControllerInput {
    
    func displayImage(viewModel: Settings.Image.ViewModel)
}

protocol SettingsViewControllerOutput {
    
    func fetchImage(request: Settings.Image.Request)
}

class SettingsViewController: UIViewController, ReuseIdentifierProtocol, SettingsViewControllerInput {
    
    var output: SettingsViewControllerOutput!
    var router: SettingsRouter!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        
        SettingsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.fetchImageOnLoad()
    }
    
    // MARK: - Event handling
    
    func fetchImageOnLoad() {
        
        let request = Settings.Image.Request()
        output.fetchImage(request: request)
    }
    
    // MARK: - Display logic
    
    @IBOutlet weak var imageView: UIImageView!
    
    func displayImage(viewModel: Settings.Image.ViewModel) {
        
        let imageName = viewModel.imageName
        let image = UIImage(named: imageName)
        
        self.imageView.image = image
    }
}
