//
//  SettingsConfigurator.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension SettingsViewController: SettingsPresenterOutput {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        
        router.passDataToNextScene(segue: segue)
    }
}

extension SettingsInteractor: SettingsViewControllerOutput {
}

extension SettingsPresenter: SettingsInteractorOutput {
}

class SettingsConfigurator {
    
    // MARK: - Object lifecycle
    
    static let sharedInstance = SettingsConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(viewController: SettingsViewController) {
        
        let router = SettingsRouter()
        router.viewController = viewController
        
        let presenter = SettingsPresenter()
        presenter.output = viewController
        
        let interactor = SettingsInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
