//
//  SettingsPresenter.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SettingsPresenterInput {
    
  func presentImage(response: Settings.Image.Response)
}

protocol SettingsPresenterOutput: class {
    
  func displayImage(viewModel: Settings.Image.ViewModel)
}

class SettingsPresenter: SettingsPresenterInput {
    
  weak var output: SettingsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentImage(response: Settings.Image.Response) {
    
    let imageName = response.imageName
    
    let viewModel = Settings.Image.ViewModel(imageName: imageName)
    self.output.displayImage(viewModel: viewModel)
  }
}
