//
//  MainInteractor.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainInteractorInput {
    
    func changeTitle(request: Main.Title.Request)
}

protocol MainInteractorOutput {
    
    func presentTitle(response: Main.Title.Response)
}

class MainInteractor: MainInteractorInput {
    
    var output: MainInteractorOutput!
    var worker: MainWorker!
    
    // MARK: - Business logic
    
    func changeTitle(request: Main.Title.Request) {
        
        let item = request.selected
        let title = item.rawValue
        
        let response = Main.Title.Response(selected: title)
        self.output.presentTitle(response: response)
    }
}
