//
//  MainPresenter.swift
//  Comics
//
//  Created by Alex Zbirnik on 25.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainPresenterInput {
    
    func presentTitle(response: Main.Title.Response)
}

protocol MainPresenterOutput: class {
    
    func displayTitle(viewModel: Main.Title.ViewModel)
}

class MainPresenter: MainPresenterInput {
    
    weak var output: MainPresenterOutput!
    
    // MARK: - Presentation logic
    
    func presentTitle(response: Main.Title.Response) {
        
        let title = response.selected
        let viewModel = Main.Title.ViewModel(title: title)
        self.output.displayTitle(viewModel: viewModel)
    }
}
