//
//  AboutUsModels.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct AboutUs {
    
  struct Description {
    
    struct Request {
    }
    struct Response {
        
        var text: String
    }
    struct ViewModel {
        
        var text: String
    }
  }
}
