//
//  AboutUsConfigurator.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension AboutUsViewController: AboutUsPresenterOutput {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        
        router.passDataToNextScene(segue: segue)
    }
}

extension AboutUsInteractor: AboutUsViewControllerOutput {
}

extension AboutUsPresenter: AboutUsInteractorOutput {
}

class AboutUsConfigurator{
    
    // MARK: - Object lifecycle
    
    static let sharedInstance = AboutUsConfigurator()
    
    private init(){}
    
    // MARK: - Configuration
    
    func configure(viewController: AboutUsViewController) {
        
        let router = AboutUsRouter()
        router.viewController = viewController
        
        let presenter = AboutUsPresenter()
        presenter.output = viewController
        
        let interactor = AboutUsInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
