//
//  AboutUsViewController.swift
//  Comics
//
//  Created by Alex Zbirnik on 26.03.17.
//  Copyright (c) 2017 com.alexzbirnik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AboutUsViewControllerInput {
    
    func displayAboutUsText(viewModel: AboutUs.Description.ViewModel)
}

protocol AboutUsViewControllerOutput {
    
    func fetchAboutUsText(request: AboutUs.Description.Request)
}

class AboutUsViewController: UIViewController, ReuseIdentifierProtocol, AboutUsViewControllerInput {
    
    var output: AboutUsViewControllerOutput!
    var router: AboutUsRouter!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        
        AboutUsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.fetchAboutUsTextOnLoad()
    }
    
    // MARK: - Event handling
    
    func fetchAboutUsTextOnLoad() {
        
        let request = AboutUs.Description.Request()
        self.output.fetchAboutUsText(request: request)
    }
    
    // MARK: - Display logic
    
    @IBOutlet weak var aboutUsLabel: UILabel!
    
    func displayAboutUsText(viewModel: AboutUs.Description.ViewModel) {
        self.aboutUsLabel.text = viewModel.text
    }
}
